### PR TITLE
Docs and readme

### PR DESCRIPTION
**Pull request by traverseda**

### CODE REVIEW

**Comment by JoelLinn** [comment]
I am sorry but I decided to remove the docs for now (As this module isn't something new, its supposed to work just like the libraries it wraps). Also the Readme isn't accurate (Except for imgui, the bindings were written by hand).

I agree though that it may not be that easy for a python guy without C++ background to get started with this as it may be unnatural to look up the c++ docs. I'm aiming to solve that with added examples.

**Comment by traverseda** [comment]
Sure, worth noting that the imgui docs aren't very good either though.

Take a look at the [pyimgui docs](https://pyimgui.readthedocs.io/en/latest/reference/imgui.core.html) as an example. The next step, if you had of accepted this pull request, would have been to start adding graphical examples to the docs.

I really don't think the cpp imgui/mahi-gui docs are a very good reference and while it might make sense to try to make the docs better starting with upstream python had very good tools for automating documentation generation. See included screenshot-generating script (very early draft), which I would have started adding into test cases if this had been well received. Unfortunately I've started a full time job and don't think I could do the kind of time commitment.

https://gist.github.com/4442cdca406b7739b91a5a986fa4b411

**Comment by JoelLinn** [comment]
That's a neat idea for capturing screenshots, might use that for generating some images statically. Imho it can't run on Travis/Appveyor though because they don't support OpenGL3 (or GLSL 150).

**Comment by traverseda** [comment]
Are there any options for running this on travis/appveyor?

**Comment by JoelLinn** [comment]
As long as they don't provide GPU acceleration no. Mesa (linux) has a OpenGL software implementation but afaik lacks the needed GLSL (OpenGL Shader Language) version. 
Also, on a headless system mahi-gui code would crash, as it tries to create a window using GLFW but there is no display server running. (Although this could likely be made to work by starting a headless X-Server)

**Comment by traverseda** [comment]
Yeah, means that test cases are pretty much not going to run on travis/appveyor, so there's no real reason to worry about them.

**Pull request closed without merging**
